const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Behaviors.jumpthru,
		C3.Behaviors.LOS,
		C3.Plugins.Text,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Keyboard.Cnds.IsKeyDown
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{DestroyOutsideLayout: 0},
	{ScrollTo: 0},
	{JOE: 0},
	{Solid: 0},
	{Jumpthru: 0},
	{PlatformJungle: 0},
	{Sky: 0},
	{Lava: 0},
	{LineOfSight: 0},
	{Charger: 0},
	{doritoOfTime: 0},
	{Text: 0},
	{junglebg: 0},
	{PlatformVolcano: 0},
	{Volcanobg: 0},
	{Spike: 0},
	{chase: 0},
	{patrool: 0},
	{soldier: 0},
	{Cheeze: 0},
	{Dirt: 0},
	{Sun: 0},
	{EmeraldPillar: 0},
	{TemplePlataform: 0},
	{TempleBG: 0},
	{HellPlataform: 0},
	{Sprite: 0},
	{HEALTH: 0},
	{GeneralObesious: 0},
	{Bullet: 0},
	{Spear: 0},
	{DAGGER: 0},
	{Keyboard: 0}
];

self.InstanceType = {
	JOE: class extends self.ISpriteInstance {},
	PlatformJungle: class extends self.ISpriteInstance {},
	Sky: class extends self.ISpriteInstance {},
	Lava: class extends self.ISpriteInstance {},
	Charger: class extends self.ISpriteInstance {},
	doritoOfTime: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	junglebg: class extends self.ISpriteInstance {},
	PlatformVolcano: class extends self.ISpriteInstance {},
	Volcanobg: class extends self.ISpriteInstance {},
	Spike: class extends self.ISpriteInstance {},
	soldier: class extends self.ISpriteInstance {},
	Cheeze: class extends self.ISpriteInstance {},
	Dirt: class extends self.ISpriteInstance {},
	Sun: class extends self.ISpriteInstance {},
	EmeraldPillar: class extends self.ISpriteInstance {},
	TemplePlataform: class extends self.ISpriteInstance {},
	TempleBG: class extends self.ISpriteInstance {},
	HellPlataform: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	GeneralObesious: class extends self.ISpriteInstance {},
	Spear: class extends self.ISpriteInstance {},
	DAGGER: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {}
}